In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# 1D array
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

# 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Special arrays
zeros = np.zeros((2,3))
ones = np.ones((3,3))
range_arr = np.arange(1, 11)
print(zeros)
print(ones)
print(range_arr)

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
##Indexing aur Slicing
print(arr1[0])       # pehla element
print(arr1[-1])      # last element
print(arr1[1:4])     # slicing
print(arr2[0, 1])     # 2D indexing (row, col)
print(arr2[:, 1])     # pura column nikalna

10
50
[20 30 40]
2
[2 5]


In [5]:
##Mathematical operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)     # addition
print(a - b)     # subtraction
print(a * b)     # multiplication
print(a / b)     # division

print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.sqrt(a))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
6
2.0
3
1
[1.         1.41421356 1.73205081]


In [7]:
##students marks
marks = np.array([85, 90, 78, 92, 60])
print("Average marks:", np.mean(marks))
print("Highest marks:", np.max(marks))
print("Lowest marks:", np.min(marks))

Average marks: 81.0
Highest marks: 92
Lowest marks: 60
